sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - truncnorm
  - future
  - future.apply
  - stats
  - graphics
  - rmarkdown
  - igraph
  - testthat
  - covr
  - knitr

cache:
  packages: true

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

email:
  on_success: change
  on_failure: change
